import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });
/*
 * config: This variable likely holds configuration options for some part of the project, such as Next.js, webpack, or Tailwind CSS. 
 * autoAddCss: This property is being set on the config object. It suggests an option related to automatically adding CSS to the project.
 * false: This value assigned to config.autoAddCss indicates that the feature of automatically adding CSS is disabled. 
 */
export const metadata = {
  title: "Ticket App",
  description: "Generated by Sachin Prajapati",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <Nav />
          <div className="flex-grow overflow-y-auto bg-page text-default-text">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
